package rules

import com.amelie.dao.*;

dialect "java"
rule "show completed tasks"
   when
      project : Project(name == 'Amelie', status == 'ongoing', phase == 'design')
      task: Task(name == 'prepare architecture documentation', task.project.id == project.id, status == 'closed')
      expert: Expert(experience == 'Architecture review', expertise > 5)
   then
      	System.out.println(expert.getName());
end;